# Generated by Django 3.0.2 on 2020-01-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='summary',
        ),
    ]
